language: objective-c
osx_image: xcode8
env:
  matrix:
    - TEST_TYPE=iOS
    - TEST_TYPE=macOS
script:
  - set -o pipefail
  - if [ "$TEST_TYPE" = "iOS" ]; then
      xcodebuild test -verbose -workspace Banana.xcworkspace -scheme Banana-iOS -sdk iphonesimulator -destination "platform=iOS Simulator,OS=10.0,name=iPhone 7" ONLY_ACTIVE_ARCH=NO;
    elif [ "$TEST_TYPE" = "macOS" ]; then
      xcodebuild test -verbose -workspace Banana.xcworkspace -scheme Banana-Mac -sdk macosx;
    fi
